### ISSUE TITLE
Laravel Version Requirement

### ISSUE THREAD

**Issue by Zaskoda** [PrimitiveSocial/openapi-initializer#3]
Installation of composer package failed for me. The error message seems to suggest that Laravel 8 is required and we're on Laravel 7. I don't see requirement information listed in the documentation and, after scanning the composer.json file, I'm not sure where it's coming from. If it is a requirement, would be handy to add it to the README.md 

```
  Problem 1
    - Installation request for primitive/openapi-initializer ^1.1 -> satisfiable by primitive/openapi-initializer[1.1.0].
    - Can only install one of: laravel/framework[v7.30.4, 8.x-dev].
    - Can only install one of: laravel/framework[8.x-dev, v7.30.4].
    - Can only install one of: laravel/framework[8.x-dev, v7.30.4].
    - Conclusion: install laravel/framework 8.x-dev
    - Installation request for laravel/framework (locked at v7.30.4, required as ^7.0) -> satisfiable by laravel/framework[v7.30.4].

```

**Comment by matthewtrask** [comment]
@Zaskoda thanks for the issue report. I will take a look hopefully this evening and get a fix pushed up.

**Comment by matthewtrask** [comment]
@Zaskoda I have tagged a new release `1.3.0` that allows for installation on both 7.x and 6.x of Laravel. It also removes the hard dependency on php 7.4 as well. 

I will update the docs with the requirements, but please let me know if you run into any more issues.
